### ISSUE TITLE
Reformular interface pública do site boas práticas para desassociá-lo da temática ODS3

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/best-practices-wp-plugin#10]
- Deixar a cor mais próxima do institucional OPAS/OMS
- Colocar logo OPAS/OMS no banner
- Dar mais destaque para a caixa de busca
- Retirar as 3 imagens e transformar esta área em carrossel
- Criar uma sessão de destaque para Registro de Boas Práticas
- Usar o link do sistema de gestão de BP
- Retirar a caixa resumo no menu direito da página de visualização da boa prática

**Comment by marcioalvessilva** [comment]
@renatomurasaki , @wilsonmoura 
Link para mockup atualizado, caso layout não altere as cores para o padrão OPAS, lembrar de limpar o cache.

http://mockups.teste.bireme.org/boaspraticas/
Aguardo feedback

**Comment by marcioalvessilva** [comment]
Etapa concluída!
