### ISSUE TITLE
Alterações — Perfil Públlico 

### ISSUE THREAD

**Issue by isabellaabe** [bireme/best-practices-wp-plugin#16]
Boa tarde!
Seguem algumas aterações no perfil público:

1) Alteração da logo da OPAS na parte superior e esquerda da página - logos nos 3 idiomas e exemplo em anexo. 
![logo_alteracao](https://user-images.githubusercontent.com/102256433/175361852-9e53a7f2-ede2-4d1e-97e4-a3690f183f7d.png)
[120-logo-color-EN.pdf](https://github.com/bireme/best-practices-wp-plugin/files/8969549/120-logo-color-EN.pdf)
[120-logo-color-ES.pdf](https://github.com/bireme/best-practices-wp-plugin/files/8969550/120-logo-color-ES.pdf) 
[120-logo-color-PT.pdf](https://github.com/bireme/best-practices-wp-plugin/files/8969551/120-logo-color-PT.pdf)

2) Retirada das duas logos que estão na parte inferior da página. Ao retirar a logo que está na parte azul, ajustar para o lado esquerdo o título e texto do disclaimer (ver em enaxo).
![logo_inferior_alteracao](https://user-images.githubusercontent.com/102256433/175362352-ddd7e090-e925-4154-92ee-5401bf52363d.png)

3) Retirar as bandeirinhas dos idiomas (ver em anexo).
4) Aguardamos as orientações em relação ao menu superior/acessibilidade.
![bandeirinhas_menusuperior_alteracao](https://user-images.githubusercontent.com/102256433/175362644-bbf16566-8b05-49f1-b102-22215c59fa55.png)

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
Imagens atualizadas de acordo com os logos disponíveis em [Logos PAHO](https://paho.sharepoint.com/sites/Intra-CMU/SitePages/120th-Anniversary-of-PAHO.aspx).

**Comment by wilsonmoura** [comment]
Ajustes realizados em https://github.com/bireme/wordpress-themes/commit/465e7d3031c668e3e0708c1a1afb302897607278

**Comment by wilsonmoura** [comment]
@isabellaabe site público atualizado conforme solicitado. Favor validar.
