### ISSUE TITLE
Layout do Menu

### ISSUE THREAD

**Issue by isabellaabe** [bireme/best-practices-wp-plugin#19]
Wilson, boa tarde!

Solicito, por gentileza, alteração do layout do menu da página principal do Portal Boas Práticas da OPAS.
Ao fazer alterações no menu ele descofigurou o layout nos 3 idiomas. 

Obrigada!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados.

**Comment by marcioalvessilva** [comment]
Bom dia!
Tema atualizado no github
