### ISSUE TITLE
Criar tema de boas práticas

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/best-practices-wp-plugin#2]

**Comment by wilsonmoura** [comment]
@marcioalvessilva segue o documentos com os campos do formulário: [FORMULARIO.docx](https://github.com/bireme/best-practices-wp-plugin/files/6924732/FORMULARIOS.Y.ASSESSMENT_Concept.Note_Best.Practices_EP_DG_02062021.docx)

**Comment by marcioalvessilva** [comment]
Etapa concluída!
