### ISSUE TITLE
Filtros - interface pública

### ISSUE THREAD

**Issue by isabellaabe** [bireme/best-practices-wp-plugin#20]
Wilson, bom dia!

Na interface pública, onde aparecem os filtros (lado direito):

1. Acrescentar à lista dos filtros os resultados do campo "Please select the most appropriate outcome of the SP 20-25 (em Relevance)". 
    - O nome do filtro será: PAHO’s Strategic Plan Outcomes 
![FiltroOCM](https://user-images.githubusercontent.com/102256433/179534344-8751baff-5b52-4825-ab2a-6eeede43eb37.png)

2. Filtro "O Country/Territory Experience on SDGs" está em branco quando clicamos nele. 
![FiltroType_erro](https://user-images.githubusercontent.com/102256433/179534402-33e94340-180e-4636-8e5a-bcfad1178103.png)

Obrigada!!
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe ajustes realizados conforme solicitado.

**Comment by isabellaabe** [comment]
Wilson, boa noite!
Obrigada pela pronta resposta!
Uma coisa: no filtro criado - dos OCMs - ele está mostrando todos os valores de tudo e não só das BPs publicadas.

Você altera...?!
Abraços,
Isabella

De: Wilson da Silva Moura ***@***.***>
Enviada em: segunda-feira, 18 de julho de 2022 22:24
Para: bireme/best-practices-wp-plugin ***@***.***>
Cc: Alvarenga, Isabella Sayuri Abe (OS-) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/best-practices-wp-plugin] Filtros - interface pública (Issue #20)


@isabellaabe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fisabellaabe&data=05%7C01%7Calvareis%40paho.org%7C1b131400ccab4e45e9f608da69256c80%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637937906711358751%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=w74XKGVrWrSs7OCp9j8OWTGTe%2BCDJLB8uUuYjliIqZc%3D&reserved=0> ajustes realizados conforme solicitado.

-
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fbest-practices-wp-plugin%2Fissues%2F20%23issuecomment-1188493714&data=05%7C01%7Calvareis%40paho.org%7C1b131400ccab4e45e9f608da69256c80%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637937906711358751%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YnAz42L55E4usSzrybPS5rVkyIR1mEPi%2Fj6RNNLODLk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYME6MPSP3KX23LFMHHXB53VUX7UVANCNFSM534PC4ZA&data=05%7C01%7Calvareis%40paho.org%7C1b131400ccab4e45e9f608da69256c80%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637937906711358751%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dOrdIdtFUff1wZDn2NKVMt25PjpVz%2BBpEfIjJV2UHP8%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by wilsonmoura** [comment]
@isabellaabe poderia nos mostrar um exemplo?
