### ISSUE TITLE
Ajuste do Layout - nome do Portal - interface pública

### ISSUE THREAD

**Issue by isabellaabe** [bireme/best-practices-wp-plugin#24]
Wilson, bom dia!
Tudo bom?

Precisamos fazer um ajuste no layout da interface pública. Precisamos deixar o nome do site (que está ao lado do logo da OPAS) em uma só linha. Esta alteração precisa ser nos 3 idiomas. 

Obrigada!

Isabella

**Comment by isabellaabe** [comment]
OI Wilson! 
Só para complementar:
O nome do Portal fica só com as primeiras letras em maiúsculo. Ou seja, ficariam assim:
Best Practices Portal
Portal de Buenas Prácticas 
Portal de Boas Práticas

**Comment by wilsonmoura** [comment]
Reasilvido em #7ab4b7a252811314b53448468333f6b28dd979c4

**Comment by wilsonmoura** [comment]
Resolvido em [7ab4b7a252811314b53448468333f6b28dd979c4](https://github.com/bireme/wordpress-themes/commit/7ab4b7a252811314b53448468333f6b28dd979c4)
