### ISSUE TITLE
Título no Portal - tamanho do campo

### ISSUE THREAD

**Issue by isabellaabe** [bireme/best-practices-wp-plugin#25]
Wilson, boa tarde!
Tudo bom?

No início do Portal, onde temos o nome, sería possível habilitar uma segunda linha para podermos incluir um subtítulo? Segue abaixo uma imagem para que você possa ver como poderia ficar. 

![image](https://github.com/bireme/best-practices-wp-plugin/assets/102256433/b5e18502-f0c8-428a-a101-89023d87236c)

Seria nos 3 idiomas e os textos seriam:

- Good Practices Portal
Experiences and Lessons Learned from the Americas 

- Portal de Mejores Prácticas
Experiencias y Lecciones Aprendidas de las Américas 

- Portal de Melhores Práticas
Experiências e lições aprendidas das Américas

Obrigada!

Abraços,
Isabella

**Comment by wilsonmoura** [comment]
Realizado em bireme/wordpress-themes#171
