### ISSUE TITLE
Troca de texto na home do Portal

### ISSUE THREAD

**Issue by isabellaabe** [bireme/best-practices-wp-plugin#26]
Wilson, Boa tarde!
Tudo bom?

Você poderia alterar para nós o seguinte texto que está na home do Portal de BP (nos 3 idiomas)?

Onde está: Click here to submit your Best Practice
Por: Click here and register your Good Practice

Onde está: Haga clic aquí y registre su Buena Práctica
Por: Haga clic aquí y registre su Mejor Práctica

Onde está: Clique aqui e cadastre sua Boa Prática
Por: Clique aqui e cadastre sua Melhor Prática

Obrigada!
Abraços,
Isabella

**Comment by wilsonmoura** [comment]
Realizado em bireme/wordpress-themes#172
