### ISSUE TITLE
Template de página para as Call for Good Practices

### ISSUE THREAD

**Issue by isabellaabe** [bireme/best-practices-wp-plugin#29]
Oi Wilson, boa tarde!

Gostaria de ver com você, se é possível na nossa página no WordPress, a criação de uma página para os Call for Good Practices. A ideia é que fosse mais ou menos igual a página da Revista da OPAS: https://www.paho.org/journal/es/numeros-especiales.

Se for possível a criação do template ou de algo igual ou semelhante, quanto tempo levaria esse trabalho?

Aguardo seu retorno.

Obrigada!
Abraços, 
Isabella

**Comment by isabellaabe** [comment]
Outra pergunta:

Caso seja possível criar esse template:

- Seria possível criar um filtro? 
- Seria possível incluir tags / keywords? (para que seja possível o filtro)?


Abraços, 
Isabella

**Comment by wilsonmoura** [comment]
@isabellaabe template disponivel no ambiente de testes: https://bestpractices.teste.bvsalud.org/calls-for-good-practices/

Favor validar para que possamos publicar no ambiente de produção..

**Comment by AugustoBaron** [comment]
Estimados @wilsonmoura y @marcioalvessilva ,

Agradecemos plenamente la rápida implementación de este cambio. Realizando la validación del template, hemos visto que no son visibles los Captions en las Featured Images del post:
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/cd253506-aaa9-4dc0-8f3b-f2f688ed1ae8)

Sería posible que se facilitara la activación de un plugin como este: https://wordpress.org/plugins/fsm-custom-featured-image-caption/ ? E adicionalmente, personalizar el CSS para que este caption siempre sea con letra tamaño 8, color #ABB8C3 ? Para que pueda aparecer algo así:
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/d3370c3e-8790-44b6-ab81-be9f6a8e7d26)

Quedo pendiente a vuestros comentarios.

Muchas gracias,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos los ajustes requeridos en el ambiente de pruebas:

https://bestpractices.teste.bvsalud.org/calls-for-good-practices/

**Comment by AugustoBaron** [comment]
Estimados @wilsonmoura y @marcioalvessilva ,

Después de ejecutar diversas pruebas, consideramos esta actualización lista para pasar al ambiente de producción. Si fuera posible dejar esta página con acceso a través de un enlace en el Menú "Calls for Good Practices" les agradecería (sin el drop-down menu que está en el ambiente de test por el momento). 

Asimismo, hemos actualizado varias de las traducciones al Español, por lo que si al migrar este elemento a la versión pública, también podría hacerse lo mismo con el kit de traducciones al Español, estaríamos muy agradecidos.

Quedo atento a cualquier comentario.

Muchas gracias por su apoyo,
Augusto

**Comment by AugustoBaron** [comment]
Estimados,

Quisiéramos consultarles si, ¿Hay algún estimado de tiempo para la implementación final de esta actualización?

Quedo al pendiente.

Saludos,
Augusto.

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos la publicación de la página para las calls en la versión live:

https://portalbp.paho.org/calls-for-good-practices/

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura,

Confirmo que la actualización ha sido correctamente implementada. Muchas gracias por el apoyo.
