### ISSUE TITLE
Visibilizar los metadatos de "Calls for Good Practices"

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/best-practices-wp-plugin#30]
Estimado @wilsonmoura y resto del equipo,

Agradecemos mucho su apoyo en los últimos días. Una disculpa, no he agregado los assignees/labels del issue ya que parece no tengo acceso a hacerlo en este GitHub por el momento.

En las actualizaciones recientes realizadas al Portal, se agregó la nueva lista controlada llamada "Calls for Good Practices" (https://admin.bestpractices.teste.bvsalud.org/admin/controlled-list/call).

Deseamos solicitar que el metadato asignado a cada GP sea visible dentro de su página de publicación de esta manera:
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/7ac740cc-f53e-4066-8f16-e8f13fc9a933)

Y que adicionalmente, se habilite este metadato como opción de filtrado en el directorio principal:
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/66e00c69-3a9e-4082-978c-5995c47d37df)

Quedo pendiente de cualquier comentario.

Atentamente,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron hicimos algunos ajustes. Por favor, haga una prueba en https://bestpractices.teste.bvsalud.org

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Hemos revisado los ajustes, y todo parece funcionar según lo esperado. Consideramos listos los cambios para pasar al ambiente de producción. 

Muchas gracias!

Att.
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron el ambiente de producción se encontra actualizado.
