### ISSUE TITLE
Activar opción para páginas en francés dentro del Portal + cambios de palabras

### ISSUE THREAD

**Issue by AugustoBaron** [bireme/best-practices-wp-plugin#32]
Estimados colegas,

Buen día.

Quisiéramos solicitar de por favor añadir la opción para tener las páginas en francés en la frontpage del Portal.

Con respecto a los textos que no son editables por nosotros mismos incluímos las siguientes traducciones:

- **Logo/Título de la página:**
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/09140ec8-4520-4eb2-bbf0-0e859245006a)
- Cambiar el logo de los 120 años por el "normal": 
![PAHO_logos_bottom_english](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/bce5d1bf-2a65-4a1b-8626-08674ec00c13)
- El título "Good Practices in Public Health Portal Experiences and Lessons Learned from the Americas" en francés será `Portail des bonnes pratiques en santé publique Expériences et enseignements tirés des Amériques`.

- **Disclaimer al pie de página:**
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/9ac0706c-2f2d-46d2-abb6-18d6c688c9bf)
- El texto traducido será:
`CLAUSE DE NON-RESPONSABILITÉ
Certains des documents ou informations auxquels l’utilisateur peut accéder via ce site peuvent appartenir à des tiers ; l’OPS ne garantit pas leur exactitude et ne sera pas responsable envers l’utilisateur ou envers les tiers d’une quelconque réclamation résultant de leur utilisation. Il est possible que le site ou les documents contiennent des informations provenant de sites externes ou des liens vers des sites externes qui ne sont ni gérés par l’OPS ni liés à l’OPS. Ces liens et informations ne sont inclus qu’aux fins de référence et leur inclusion ne suppose pas l’approbation ou l’aval de l’OPS. L’OPS n’assume aucune responsabilité relativement aux informations contenues sur ces sites externes ou aux actions ou omissions des parties ou des fournisseurs qui y sont mentionnés.`
- El link al final llevará como traducción:
`CONDITIONS GÉNÉRALES D’UTILISATION DU SITE`

- **"Good Practices" widget en frontpage:**
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/15d577e4-3d0e-4f11-a14d-7df5ba57c5b0)
- Traducción del título: `Dernières bonnes pratiques`

- **Footer:**
![image](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/30079d07-3048-4cc4-9827-3c03ce037eea)
La traducción será:
`Conditions générales d'utilisation | Politique de confidentialité
Bureau régional pour les Amériques de l'Organisation mondiale de la santé
© Organisation panaméricaine de la santé. Tous droits réservés.`

*******************
Quedo pendiente de cualquier comentario, favor comunicar cualquier contenido adicional que quiera de traducción. Si hay pages a las que tenemos acceso para edirar que ocupan traducción, solicitamos enlazar una copia de la versión en inglés y después nosotros reemplazaremos e indicárnoslo.

Siempre gracias por su tiempo y apoyo. 

Atentamente,
Augusto

**Comment by wilsonmoura** [comment]
@AugustoBaron ya hicimos algunos ajustes. Enviamos las listas de textos adjuntas que deben traducirse al francés. Después de eso, por favor adjunte la lista actualizada a este issue para que podamos incorporar el idioma francés en el sitio público.

[gp-english.txt](https://github.com/bireme/best-practices-wp-plugin/files/14276021/gp-english.txt)
[gp-theme-english.txt](https://github.com/bireme/best-practices-wp-plugin/files/14276024/gp-theme-english.txt)

**Comment by wilsonmoura** [comment]
@AugustoBaron también necesitamos de las imágenes en portugués, español y francés.

**Comment by AugustoBaron** [comment]
@wilsonmoura Muchas gracias por la actualización.

Envío a continuación los documentos traducidos y las imágenes faltantes:

[gp-theme-english.txt](https://github.com/bireme/best-practices-wp-plugin/files/14284317/gp-theme-english.txt)
[gp-english.txt](https://github.com/bireme/best-practices-wp-plugin/files/14284318/gp-english.txt)
![PAHO_logos_bottom_english](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/d4f82c46-edb8-43d1-bc03-6a1080bba0a7)
![PAHO_logos_bottom_french](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/8b4c537f-8e68-4040-a68f-0b1a5414d314)
![PAHO_logos_bottom_portuguese](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/ab37ab9d-23de-42b9-88c6-5e816660bce4)
![PAHO_logos_bottom_spanish](https://github.com/bireme/best-practices-wp-plugin/assets/124937355/662b8c4d-56fd-4609-aca1-d713aa014eb7)

Solo como comentario aparte, hemos actualizado el menú, las páginas, y el formato de contacto en la sección de francés. Sin embargo, el título del Portal ha vuelto al inglés. 

Quedo pendiente de cualquier comentario.

Saludos.

**Comment by AugustoBaron** [comment]
Un comentario adicional, hemos visto que no importa el tipo de resolución que usemos ni el formato, las imágenes que subimos de banner salen borrosas.

¿Es posible instalar el plug-in [SVG Support plug-in ](https://wordpress.org/plugins/svg-support/) para poder usar imágenes de vector como banners?

¡Gracias!

**Comment by AugustoBaron** [comment]
Estimado @wilsonmoura ,

Como comentario para la validación de este issue, todavía estaría pendiente la actualización de los logos para todas las lenguas, y poner el título del homepage en francés (sale en inglés).

Asimismo, quisiera hacer saber que este es mi último día en la organización, por lo tanto estará Isabella dando seguimiento a estos issues!

Saludos y muchas gracias.

**Comment by wilsonmoura** [comment]
@isabellaabe os ajustes foram realizados conforme solicitados. Favor validar no ambiente de testes:

https://bestpractices.teste.bvsalud.org/

**Comment by isabellaabe** [comment]
@wilsonmoura , Boa tarde!!
Acabo de revisar o ambiente de produção e estes ajustes já foram implementados lá, correto?
Abraços,
Isabella
